import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import { ProductCard } from "~/components/ProductCard";
import headphone from "~/assets/images/headphone.png";
import { roboto } from "~/fonts";

const products = [
  {
    id: 1,
    image: headphone,
    name: "Zebronics head phone",
    price: 19.99,
    description:
      "A portable headphone with a battery life of 20 hours and IP67 rating. Comes with a 3 years warranty.",
    colors: ["#FF5733", "#33FF57", "#5733FF"],
  },
  {
    id: 2,
    image: headphone,
    name: "Example Product #2",
    price: 29.99,
    description: "Example product #2 description",
    colors: ["#FFC300", "#FF5733", "#C300FF", "#23BB42"],
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={roboto.className}>
          {products.map((product) => (
            <ProductCard
              key={product.id}
              image={product.image}
              name={product.name}
              price={product.price}
              description={product.description}
              colors={product.colors}
            />
          ))}
        </div>
      </main>
    </>
  );
}
